### ISSUE TITLE
Possible typos in Code 2.26 of page 81 in BAP3 book

### ISSUE THREAD

**Issue by ezDataCode** [aloctavodia/BAP3#17]
I think that there is a typo in line 2 of Code block 2.26 of page 81.:
`    𝜇 = pm.Normal("𝜇", mu=0, sigma=10, shape=4)`
I'm not sure if a normal distribution centered around zero is a logical prior for this example.

The text right above the code block says that the code should be "almost the same as model_g", who's mean was defined in Code 2.12 of page 66 as:
`    𝜇 = pm.Uniform('𝜇', lower=40, upper=70)`

But Code 2.27 of page 82 is described as an alternative syntax to Code 2.26 and the mean was defined there as:
`    𝜇 = pm.HalfNormal("𝜇", sigma=5, dims="days")`

Is a correction needed to avoid confusion?

**Comment by aloctavodia** [comment]
I see how this can be confusing. 

In the text I am loosely connecting models, without enough background or motivation. 

* Most priors in the book are vague or sometimes weakly informative. For instance 𝜇 = pm.Uniform('𝜇', lower=40, upper=70. is just wider than the observed data (and also wider than the not-yet observed data, for this problem). We usually avoid setting uniform priors, unless the boundaries has some physical meaning and we want to avoid values outside that range. Instead of this uniform distribution, we could have used something like Normal(mu=55,sigma=6) for a similar effect.


* When comparing groups in many fields a model 2.26 will arise as a "default model", is something you may find commonly used in the literature or when discussing with people. Is a model that makes sense when the observed quantity can take negative an positive values or when it can only take positive (or negative) but observation are "far away" from the zero. 

* Instead model  2.27 makes use of the information that tips are positive and we want to avoid allocation any mass/density/plausibility to negative values. One way to do that is to use reason a Gamma likelihood (and then adjust priors accordingly).

**Comment by ezDataCode** [comment]
Thank you, the background and motivation you described above for why those different priors were used in the examples helped clarify this for me. 

Thank you for your answer, and for writing this excellent book.
